/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: 8d2bd5fc4212920a4ee032ee45a9b8a819d276c5 */

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_simdutf_validate_utf8, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, string, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_simdutf_validate_ascii arginfo_simdutf_validate_utf8

#define arginfo_simdutf_validate_utf16 arginfo_simdutf_validate_utf8

#define arginfo_simdutf_validate_utf16be arginfo_simdutf_validate_utf8

#define arginfo_simdutf_validate_utf16le arginfo_simdutf_validate_utf8

#define arginfo_simdutf_validate_utf32 arginfo_simdutf_validate_utf8

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_simdutf_validate_utf8_with_errors, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, string, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_simdutf_validate_ascii_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_validate_utf16_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_validate_utf16be_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_validate_utf16le_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_validate_utf32_with_errors arginfo_simdutf_validate_utf8_with_errors

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_simdutf_count_utf8, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, string, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_simdutf_count_utf16 arginfo_simdutf_count_utf8

#define arginfo_simdutf_count_utf16be arginfo_simdutf_count_utf8

#define arginfo_simdutf_count_utf16le arginfo_simdutf_count_utf8

#define arginfo_simdutf_utf8_length_from_utf16 arginfo_simdutf_count_utf8

#define arginfo_simdutf_utf8_length_from_utf16be arginfo_simdutf_count_utf8

#define arginfo_simdutf_utf8_length_from_utf16le arginfo_simdutf_count_utf8

#define arginfo_simdutf_utf8_length_from_utf32 arginfo_simdutf_count_utf8

#define arginfo_simdutf_utf8_length_from_latin1 arginfo_simdutf_count_utf8

#define arginfo_simdutf_utf16_length_from_utf8 arginfo_simdutf_count_utf8

#define arginfo_simdutf_utf16_length_from_utf32 arginfo_simdutf_count_utf8

#define arginfo_simdutf_utf16_length_from_latin1 arginfo_simdutf_count_utf8

#define arginfo_simdutf_utf32_length_from_utf8 arginfo_simdutf_count_utf8

#define arginfo_simdutf_utf32_length_from_utf16 arginfo_simdutf_count_utf8

#define arginfo_simdutf_utf32_length_from_utf16be arginfo_simdutf_count_utf8

#define arginfo_simdutf_utf32_length_from_utf16le arginfo_simdutf_count_utf8

#define arginfo_simdutf_latin1_length_from_utf8 arginfo_simdutf_count_utf8

#define arginfo_simdutf_latin1_length_from_utf16 arginfo_simdutf_count_utf8

#define arginfo_simdutf_latin1_length_from_utf32 arginfo_simdutf_count_utf8

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_simdutf_convert_utf8_to_latin1, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, string, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_simdutf_convert_utf8_to_utf16 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf8_to_utf16be arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf8_to_utf16le arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf8_to_utf32 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf16_to_utf8 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf16_to_latin1 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf16_to_utf32 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf16be_to_utf8 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf16be_to_utf32 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf16be_to_latin1 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf16le_to_utf8 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf16le_to_utf32 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf16le_to_latin1 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf32_to_utf8 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf32_to_utf16 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf32_to_utf16le arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf32_to_utf16be arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf32_to_latin1 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_latin1_to_utf8 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_latin1_to_utf16 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_latin1_to_utf16le arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_latin1_to_utf16be arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_latin1_to_utf32 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_utf8_to_utf16_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf8_to_utf16be_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf8_to_utf16le_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf8_to_utf32_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf8_to_latin1_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf16_to_utf8_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf16_to_utf32_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf16_to_latin1_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf16le_to_utf8_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf16le_to_latin1_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf16le_to_utf32_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf16be_to_utf8_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf16be_to_utf32_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf16be_to_latin1_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf32_to_utf8_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf32_to_utf16_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf32_to_utf16be_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf32_to_utf16le_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_utf32_to_latin1_with_errors arginfo_simdutf_validate_utf8_with_errors

#define arginfo_simdutf_convert_valid_utf8_to_latin1 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf8_to_utf16 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf8_to_utf16le arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf8_to_utf16be arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf8_to_utf32 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf16_to_utf8 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf16_to_latin1 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf16_to_utf32 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf16le_to_utf8 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf16le_to_utf32 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf16le_to_latin1 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf16be_to_utf8 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf16be_to_utf32 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf16be_to_latin1 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf32_to_latin1 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf32_to_utf8 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf32_to_utf16 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf32_to_utf16be arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_convert_valid_utf32_to_utf16le arginfo_simdutf_convert_utf8_to_latin1

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_simdutf_change_endianness_utf16, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, string, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, length, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_simdutf_trim_partial_utf8 arginfo_simdutf_change_endianness_utf16

#define arginfo_simdutf_trim_partial_utf16be arginfo_simdutf_change_endianness_utf16

#define arginfo_simdutf_trim_partial_utf16le arginfo_simdutf_change_endianness_utf16

#define arginfo_simdutf_trim_partial_utf16 arginfo_simdutf_change_endianness_utf16

#define arginfo_simdutf_autodetect_encoding arginfo_simdutf_count_utf8

#define arginfo_simdutf_detect_encodings arginfo_simdutf_count_utf8

#define arginfo_simdutf_binary_to_base64 arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_base64_to_binary arginfo_simdutf_convert_utf8_to_latin1

#define arginfo_simdutf_base64_to_binary_safe arginfo_simdutf_convert_utf8_to_latin1


ZEND_FUNCTION(simdutf_validate_utf8);
ZEND_FUNCTION(simdutf_validate_ascii);
ZEND_FUNCTION(simdutf_validate_utf16);
ZEND_FUNCTION(simdutf_validate_utf16be);
ZEND_FUNCTION(simdutf_validate_utf16le);
ZEND_FUNCTION(simdutf_validate_utf32);
ZEND_FUNCTION(simdutf_validate_utf8_with_errors);
ZEND_FUNCTION(simdutf_validate_ascii_with_errors);
ZEND_FUNCTION(simdutf_validate_utf16_with_errors);
ZEND_FUNCTION(simdutf_validate_utf16be_with_errors);
ZEND_FUNCTION(simdutf_validate_utf16le_with_errors);
ZEND_FUNCTION(simdutf_validate_utf32_with_errors);
ZEND_FUNCTION(simdutf_count_utf8);
ZEND_FUNCTION(simdutf_count_utf16);
ZEND_FUNCTION(simdutf_count_utf16be);
ZEND_FUNCTION(simdutf_count_utf16le);
ZEND_FUNCTION(simdutf_utf8_length_from_utf16);
ZEND_FUNCTION(simdutf_utf8_length_from_utf16be);
ZEND_FUNCTION(simdutf_utf8_length_from_utf16le);
ZEND_FUNCTION(simdutf_utf8_length_from_utf32);
ZEND_FUNCTION(simdutf_utf8_length_from_latin1);
ZEND_FUNCTION(simdutf_utf16_length_from_utf8);
ZEND_FUNCTION(simdutf_utf16_length_from_utf32);
ZEND_FUNCTION(simdutf_utf16_length_from_latin1);
ZEND_FUNCTION(simdutf_utf32_length_from_utf8);
ZEND_FUNCTION(simdutf_utf32_length_from_utf16);
ZEND_FUNCTION(simdutf_utf32_length_from_utf16be);
ZEND_FUNCTION(simdutf_utf32_length_from_utf16le);
ZEND_FUNCTION(simdutf_latin1_length_from_utf8);
ZEND_FUNCTION(simdutf_latin1_length_from_utf16);
ZEND_FUNCTION(simdutf_latin1_length_from_utf32);
ZEND_FUNCTION(simdutf_convert_utf8_to_latin1);
ZEND_FUNCTION(simdutf_convert_utf8_to_utf16);
ZEND_FUNCTION(simdutf_convert_utf8_to_utf16be);
ZEND_FUNCTION(simdutf_convert_utf8_to_utf16le);
ZEND_FUNCTION(simdutf_convert_utf8_to_utf32);
ZEND_FUNCTION(simdutf_convert_utf16_to_utf8);
ZEND_FUNCTION(simdutf_convert_utf16_to_latin1);
ZEND_FUNCTION(simdutf_convert_utf16_to_utf32);
ZEND_FUNCTION(simdutf_convert_utf16be_to_utf8);
ZEND_FUNCTION(simdutf_convert_utf16be_to_utf32);
ZEND_FUNCTION(simdutf_convert_utf16be_to_latin1);
ZEND_FUNCTION(simdutf_convert_utf16le_to_utf8);
ZEND_FUNCTION(simdutf_convert_utf16le_to_utf32);
ZEND_FUNCTION(simdutf_convert_utf16le_to_latin1);
ZEND_FUNCTION(simdutf_convert_utf32_to_utf8);
ZEND_FUNCTION(simdutf_convert_utf32_to_utf16);
ZEND_FUNCTION(simdutf_convert_utf32_to_utf16le);
ZEND_FUNCTION(simdutf_convert_utf32_to_utf16be);
ZEND_FUNCTION(simdutf_convert_utf32_to_latin1);
ZEND_FUNCTION(simdutf_convert_latin1_to_utf8);
ZEND_FUNCTION(simdutf_convert_latin1_to_utf16);
ZEND_FUNCTION(simdutf_convert_latin1_to_utf16le);
ZEND_FUNCTION(simdutf_convert_latin1_to_utf16be);
ZEND_FUNCTION(simdutf_convert_latin1_to_utf32);
ZEND_FUNCTION(simdutf_convert_utf8_to_utf16_with_errors);
ZEND_FUNCTION(simdutf_convert_utf8_to_utf16be_with_errors);
ZEND_FUNCTION(simdutf_convert_utf8_to_utf16le_with_errors);
ZEND_FUNCTION(simdutf_convert_utf8_to_utf32_with_errors);
ZEND_FUNCTION(simdutf_convert_utf8_to_latin1_with_errors);
ZEND_FUNCTION(simdutf_convert_utf16_to_utf8_with_errors);
ZEND_FUNCTION(simdutf_convert_utf16_to_utf32_with_errors);
ZEND_FUNCTION(simdutf_convert_utf16_to_latin1_with_errors);
ZEND_FUNCTION(simdutf_convert_utf16le_to_utf8_with_errors);
ZEND_FUNCTION(simdutf_convert_utf16le_to_latin1_with_errors);
ZEND_FUNCTION(simdutf_convert_utf16le_to_utf32_with_errors);
ZEND_FUNCTION(simdutf_convert_utf16be_to_utf8_with_errors);
ZEND_FUNCTION(simdutf_convert_utf16be_to_utf32_with_errors);
ZEND_FUNCTION(simdutf_convert_utf16be_to_latin1_with_errors);
ZEND_FUNCTION(simdutf_convert_utf32_to_utf8_with_errors);
ZEND_FUNCTION(simdutf_convert_utf32_to_utf16_with_errors);
ZEND_FUNCTION(simdutf_convert_utf32_to_utf16be_with_errors);
ZEND_FUNCTION(simdutf_convert_utf32_to_utf16le_with_errors);
ZEND_FUNCTION(simdutf_convert_utf32_to_latin1_with_errors);
ZEND_FUNCTION(simdutf_convert_valid_utf8_to_latin1);
ZEND_FUNCTION(simdutf_convert_valid_utf8_to_utf16);
ZEND_FUNCTION(simdutf_convert_valid_utf8_to_utf16le);
ZEND_FUNCTION(simdutf_convert_valid_utf8_to_utf16be);
ZEND_FUNCTION(simdutf_convert_valid_utf8_to_utf32);
ZEND_FUNCTION(simdutf_convert_valid_utf16_to_utf8);
ZEND_FUNCTION(simdutf_convert_valid_utf16_to_latin1);
ZEND_FUNCTION(simdutf_convert_valid_utf16_to_utf32);
ZEND_FUNCTION(simdutf_convert_valid_utf16le_to_utf8);
ZEND_FUNCTION(simdutf_convert_valid_utf16le_to_utf32);
ZEND_FUNCTION(simdutf_convert_valid_utf16le_to_latin1);
ZEND_FUNCTION(simdutf_convert_valid_utf16be_to_utf8);
ZEND_FUNCTION(simdutf_convert_valid_utf16be_to_utf32);
ZEND_FUNCTION(simdutf_convert_valid_utf16be_to_latin1);
ZEND_FUNCTION(simdutf_convert_valid_utf32_to_latin1);
ZEND_FUNCTION(simdutf_convert_valid_utf32_to_utf8);
ZEND_FUNCTION(simdutf_convert_valid_utf32_to_utf16);
ZEND_FUNCTION(simdutf_convert_valid_utf32_to_utf16be);
ZEND_FUNCTION(simdutf_convert_valid_utf32_to_utf16le);
ZEND_FUNCTION(simdutf_change_endianness_utf16);
ZEND_FUNCTION(simdutf_trim_partial_utf8);
ZEND_FUNCTION(simdutf_trim_partial_utf16be);
ZEND_FUNCTION(simdutf_trim_partial_utf16le);
ZEND_FUNCTION(simdutf_trim_partial_utf16);
ZEND_FUNCTION(simdutf_autodetect_encoding);
ZEND_FUNCTION(simdutf_detect_encodings);
ZEND_FUNCTION(simdutf_binary_to_base64);
ZEND_FUNCTION(simdutf_base64_to_binary);
ZEND_FUNCTION(simdutf_base64_to_binary_safe);


static const zend_function_entry ext_functions[] = {
	ZEND_FE(simdutf_validate_utf8, arginfo_simdutf_validate_utf8)
	ZEND_FE(simdutf_validate_ascii, arginfo_simdutf_validate_ascii)
	ZEND_FE(simdutf_validate_utf16, arginfo_simdutf_validate_utf16)
	ZEND_FE(simdutf_validate_utf16be, arginfo_simdutf_validate_utf16be)
	ZEND_FE(simdutf_validate_utf16le, arginfo_simdutf_validate_utf16le)
	ZEND_FE(simdutf_validate_utf32, arginfo_simdutf_validate_utf32)
	ZEND_FE(simdutf_validate_utf8_with_errors, arginfo_simdutf_validate_utf8_with_errors)
	ZEND_FE(simdutf_validate_ascii_with_errors, arginfo_simdutf_validate_ascii_with_errors)
	ZEND_FE(simdutf_validate_utf16_with_errors, arginfo_simdutf_validate_utf16_with_errors)
	ZEND_FE(simdutf_validate_utf16be_with_errors, arginfo_simdutf_validate_utf16be_with_errors)
	ZEND_FE(simdutf_validate_utf16le_with_errors, arginfo_simdutf_validate_utf16le_with_errors)
	ZEND_FE(simdutf_validate_utf32_with_errors, arginfo_simdutf_validate_utf32_with_errors)
	ZEND_FE(simdutf_count_utf8, arginfo_simdutf_count_utf8)
	ZEND_FE(simdutf_count_utf16, arginfo_simdutf_count_utf16)
	ZEND_FE(simdutf_count_utf16be, arginfo_simdutf_count_utf16be)
	ZEND_FE(simdutf_count_utf16le, arginfo_simdutf_count_utf16le)
	ZEND_FE(simdutf_utf8_length_from_utf16, arginfo_simdutf_utf8_length_from_utf16)
	ZEND_FE(simdutf_utf8_length_from_utf16be, arginfo_simdutf_utf8_length_from_utf16be)
	ZEND_FE(simdutf_utf8_length_from_utf16le, arginfo_simdutf_utf8_length_from_utf16le)
	ZEND_FE(simdutf_utf8_length_from_utf32, arginfo_simdutf_utf8_length_from_utf32)
	ZEND_FE(simdutf_utf8_length_from_latin1, arginfo_simdutf_utf8_length_from_latin1)
	ZEND_FE(simdutf_utf16_length_from_utf8, arginfo_simdutf_utf16_length_from_utf8)
	ZEND_FE(simdutf_utf16_length_from_utf32, arginfo_simdutf_utf16_length_from_utf32)
	ZEND_FE(simdutf_utf16_length_from_latin1, arginfo_simdutf_utf16_length_from_latin1)
	ZEND_FE(simdutf_utf32_length_from_utf8, arginfo_simdutf_utf32_length_from_utf8)
	ZEND_FE(simdutf_utf32_length_from_utf16, arginfo_simdutf_utf32_length_from_utf16)
	ZEND_FE(simdutf_utf32_length_from_utf16be, arginfo_simdutf_utf32_length_from_utf16be)
	ZEND_FE(simdutf_utf32_length_from_utf16le, arginfo_simdutf_utf32_length_from_utf16le)
	ZEND_FE(simdutf_latin1_length_from_utf8, arginfo_simdutf_latin1_length_from_utf8)
	ZEND_FE(simdutf_latin1_length_from_utf16, arginfo_simdutf_latin1_length_from_utf16)
	ZEND_FE(simdutf_latin1_length_from_utf32, arginfo_simdutf_latin1_length_from_utf32)
	ZEND_FE(simdutf_convert_utf8_to_latin1, arginfo_simdutf_convert_utf8_to_latin1)
	ZEND_FE(simdutf_convert_utf8_to_utf16, arginfo_simdutf_convert_utf8_to_utf16)
	ZEND_FE(simdutf_convert_utf8_to_utf16be, arginfo_simdutf_convert_utf8_to_utf16be)
	ZEND_FE(simdutf_convert_utf8_to_utf16le, arginfo_simdutf_convert_utf8_to_utf16le)
	ZEND_FE(simdutf_convert_utf8_to_utf32, arginfo_simdutf_convert_utf8_to_utf32)
	ZEND_FE(simdutf_convert_utf16_to_utf8, arginfo_simdutf_convert_utf16_to_utf8)
	ZEND_FE(simdutf_convert_utf16_to_latin1, arginfo_simdutf_convert_utf16_to_latin1)
	ZEND_FE(simdutf_convert_utf16_to_utf32, arginfo_simdutf_convert_utf16_to_utf32)
	ZEND_FE(simdutf_convert_utf16be_to_utf8, arginfo_simdutf_convert_utf16be_to_utf8)
	ZEND_FE(simdutf_convert_utf16be_to_utf32, arginfo_simdutf_convert_utf16be_to_utf32)
	ZEND_FE(simdutf_convert_utf16be_to_latin1, arginfo_simdutf_convert_utf16be_to_latin1)
	ZEND_FE(simdutf_convert_utf16le_to_utf8, arginfo_simdutf_convert_utf16le_to_utf8)
	ZEND_FE(simdutf_convert_utf16le_to_utf32, arginfo_simdutf_convert_utf16le_to_utf32)
	ZEND_FE(simdutf_convert_utf16le_to_latin1, arginfo_simdutf_convert_utf16le_to_latin1)
	ZEND_FE(simdutf_convert_utf32_to_utf8, arginfo_simdutf_convert_utf32_to_utf8)
	ZEND_FE(simdutf_convert_utf32_to_utf16, arginfo_simdutf_convert_utf32_to_utf16)
	ZEND_FE(simdutf_convert_utf32_to_utf16le, arginfo_simdutf_convert_utf32_to_utf16le)
	ZEND_FE(simdutf_convert_utf32_to_utf16be, arginfo_simdutf_convert_utf32_to_utf16be)
	ZEND_FE(simdutf_convert_utf32_to_latin1, arginfo_simdutf_convert_utf32_to_latin1)
	ZEND_FE(simdutf_convert_latin1_to_utf8, arginfo_simdutf_convert_latin1_to_utf8)
	ZEND_FE(simdutf_convert_latin1_to_utf16, arginfo_simdutf_convert_latin1_to_utf16)
	ZEND_FE(simdutf_convert_latin1_to_utf16le, arginfo_simdutf_convert_latin1_to_utf16le)
	ZEND_FE(simdutf_convert_latin1_to_utf16be, arginfo_simdutf_convert_latin1_to_utf16be)
	ZEND_FE(simdutf_convert_latin1_to_utf32, arginfo_simdutf_convert_latin1_to_utf32)
	ZEND_FE(simdutf_convert_utf8_to_utf16_with_errors, arginfo_simdutf_convert_utf8_to_utf16_with_errors)
	ZEND_FE(simdutf_convert_utf8_to_utf16be_with_errors, arginfo_simdutf_convert_utf8_to_utf16be_with_errors)
	ZEND_FE(simdutf_convert_utf8_to_utf16le_with_errors, arginfo_simdutf_convert_utf8_to_utf16le_with_errors)
	ZEND_FE(simdutf_convert_utf8_to_utf32_with_errors, arginfo_simdutf_convert_utf8_to_utf32_with_errors)
	ZEND_FE(simdutf_convert_utf8_to_latin1_with_errors, arginfo_simdutf_convert_utf8_to_latin1_with_errors)
	ZEND_FE(simdutf_convert_utf16_to_utf8_with_errors, arginfo_simdutf_convert_utf16_to_utf8_with_errors)
	ZEND_FE(simdutf_convert_utf16_to_utf32_with_errors, arginfo_simdutf_convert_utf16_to_utf32_with_errors)
	ZEND_FE(simdutf_convert_utf16_to_latin1_with_errors, arginfo_simdutf_convert_utf16_to_latin1_with_errors)
	ZEND_FE(simdutf_convert_utf16le_to_utf8_with_errors, arginfo_simdutf_convert_utf16le_to_utf8_with_errors)
	ZEND_FE(simdutf_convert_utf16le_to_latin1_with_errors, arginfo_simdutf_convert_utf16le_to_latin1_with_errors)
	ZEND_FE(simdutf_convert_utf16le_to_utf32_with_errors, arginfo_simdutf_convert_utf16le_to_utf32_with_errors)
	ZEND_FE(simdutf_convert_utf16be_to_utf8_with_errors, arginfo_simdutf_convert_utf16be_to_utf8_with_errors)
	ZEND_FE(simdutf_convert_utf16be_to_utf32_with_errors, arginfo_simdutf_convert_utf16be_to_utf32_with_errors)
	ZEND_FE(simdutf_convert_utf16be_to_latin1_with_errors, arginfo_simdutf_convert_utf16be_to_latin1_with_errors)
	ZEND_FE(simdutf_convert_utf32_to_utf8_with_errors, arginfo_simdutf_convert_utf32_to_utf8_with_errors)
	ZEND_FE(simdutf_convert_utf32_to_utf16_with_errors, arginfo_simdutf_convert_utf32_to_utf16_with_errors)
	ZEND_FE(simdutf_convert_utf32_to_utf16be_with_errors, arginfo_simdutf_convert_utf32_to_utf16be_with_errors)
	ZEND_FE(simdutf_convert_utf32_to_utf16le_with_errors, arginfo_simdutf_convert_utf32_to_utf16le_with_errors)
	ZEND_FE(simdutf_convert_utf32_to_latin1_with_errors, arginfo_simdutf_convert_utf32_to_latin1_with_errors)
	ZEND_FE(simdutf_convert_valid_utf8_to_latin1, arginfo_simdutf_convert_valid_utf8_to_latin1)
	ZEND_FE(simdutf_convert_valid_utf8_to_utf16, arginfo_simdutf_convert_valid_utf8_to_utf16)
	ZEND_FE(simdutf_convert_valid_utf8_to_utf16le, arginfo_simdutf_convert_valid_utf8_to_utf16le)
	ZEND_FE(simdutf_convert_valid_utf8_to_utf16be, arginfo_simdutf_convert_valid_utf8_to_utf16be)
	ZEND_FE(simdutf_convert_valid_utf8_to_utf32, arginfo_simdutf_convert_valid_utf8_to_utf32)
	ZEND_FE(simdutf_convert_valid_utf16_to_utf8, arginfo_simdutf_convert_valid_utf16_to_utf8)
	ZEND_FE(simdutf_convert_valid_utf16_to_latin1, arginfo_simdutf_convert_valid_utf16_to_latin1)
	ZEND_FE(simdutf_convert_valid_utf16_to_utf32, arginfo_simdutf_convert_valid_utf16_to_utf32)
	ZEND_FE(simdutf_convert_valid_utf16le_to_utf8, arginfo_simdutf_convert_valid_utf16le_to_utf8)
	ZEND_FE(simdutf_convert_valid_utf16le_to_utf32, arginfo_simdutf_convert_valid_utf16le_to_utf32)
	ZEND_FE(simdutf_convert_valid_utf16le_to_latin1, arginfo_simdutf_convert_valid_utf16le_to_latin1)
	ZEND_FE(simdutf_convert_valid_utf16be_to_utf8, arginfo_simdutf_convert_valid_utf16be_to_utf8)
	ZEND_FE(simdutf_convert_valid_utf16be_to_utf32, arginfo_simdutf_convert_valid_utf16be_to_utf32)
	ZEND_FE(simdutf_convert_valid_utf16be_to_latin1, arginfo_simdutf_convert_valid_utf16be_to_latin1)
	ZEND_FE(simdutf_convert_valid_utf32_to_latin1, arginfo_simdutf_convert_valid_utf32_to_latin1)
	ZEND_FE(simdutf_convert_valid_utf32_to_utf8, arginfo_simdutf_convert_valid_utf32_to_utf8)
	ZEND_FE(simdutf_convert_valid_utf32_to_utf16, arginfo_simdutf_convert_valid_utf32_to_utf16)
	ZEND_FE(simdutf_convert_valid_utf32_to_utf16be, arginfo_simdutf_convert_valid_utf32_to_utf16be)
	ZEND_FE(simdutf_convert_valid_utf32_to_utf16le, arginfo_simdutf_convert_valid_utf32_to_utf16le)
	ZEND_FE(simdutf_change_endianness_utf16, arginfo_simdutf_change_endianness_utf16)
	ZEND_FE(simdutf_trim_partial_utf8, arginfo_simdutf_trim_partial_utf8)
	ZEND_FE(simdutf_trim_partial_utf16be, arginfo_simdutf_trim_partial_utf16be)
	ZEND_FE(simdutf_trim_partial_utf16le, arginfo_simdutf_trim_partial_utf16le)
	ZEND_FE(simdutf_trim_partial_utf16, arginfo_simdutf_trim_partial_utf16)
	ZEND_FE(simdutf_autodetect_encoding, arginfo_simdutf_autodetect_encoding)
	ZEND_FE(simdutf_detect_encodings, arginfo_simdutf_detect_encodings)
	ZEND_FE(simdutf_binary_to_base64, arginfo_simdutf_binary_to_base64)
	ZEND_FE(simdutf_base64_to_binary, arginfo_simdutf_base64_to_binary)
	ZEND_FE(simdutf_base64_to_binary_safe, arginfo_simdutf_base64_to_binary_safe)
	ZEND_FE_END
};
